name: Orquestaci√≥n Docker
on: workflow_dipatch
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions: { packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{ github.repository_owner }}, password: ${{ secrets.GITHUB_TOKEN }} }
      - uses: docker/build-push-action@v6
        with: { push: true, tags: ghcr.io/${{ github.repository_owner }}/demo-devops-docker:latest }
  
  run:
    needs: build-push
    runs-on: ubuntu-latest
    permissions: { packages: read }
    steps:
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{ github.repository_owner }}, password: ${{ secrets.GITHUB_TOKEN }} }
      - run: |
          docker pull ghcr.io/${{ github.repository_owner }}/demo-devops-docker:latest
          echo "Ejecutando..."
          docker run --rm ghcr.io/${{ github.repository_owner }}/demo-devops-docker:latest